services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT_NUMBER=${PORT_NUMBER}
      - DB_HOST=${DB_HOST_PROD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"

#   db:
#     image: postgres:18.3
#     container_name: postgres_v18
#     environment:
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#       - POSTGRES_DB=myapp_db
#     ports:
#       - "5433:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql

# volumes:
#   pgdata:
#     external: true
