services:
  backend:
    depends_on:
      - db
      - valkey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT_NUMBER=${PORT_NUMBER}
      - DB_HOST=${DB_HOST_INTERNAL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - VALKEY_HOST=valkey
      - VALKEY_PORT=${VALKEY_PORT}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - DB_ENV=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - venv/
            - __pycache__/
            - .git/
            - logs
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: .env

  db:
    image: postgres:18.3
    container_name: postgres_v18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9.0
    container_name: valkey
    command: valkey-server --requirepass ${VALKEY_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - valkeydata:/data

volumes:
  pgdata:
    external: true
  valkeydata:
    external: true
